# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form_teach.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_test = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_test.setObjectName("tableWidget_test")
        self.tableWidget_test.setColumnCount(0)
        self.tableWidget_test.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_test)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_edit = QtWidgets.QPushButton(self.centralwidget)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        self.menu_test = QtWidgets.QMenu(self.menubar)
        self.menu_test.setObjectName("menu_test")
        MainWindow.setMenuBar(self.menubar)
        self.add_test = QtWidgets.QAction(MainWindow)
        self.add_test.setObjectName("add_test")
        self.edit_test = QtWidgets.QAction(MainWindow)
        self.edit_test.setObjectName("edit_test")
        self.delete_test = QtWidgets.QAction(MainWindow)
        self.delete_test.setObjectName("delete_test")
        self.quit = QtWidgets.QAction(MainWindow)
        self.quit.setObjectName("quit")
        self.pupil_res = QtWidgets.QAction(MainWindow)
        self.pupil_res.setObjectName("pupil_res")
        self.test_stats = QtWidgets.QAction(MainWindow)
        self.test_stats.setObjectName("test_stats")
        self.task_stats = QtWidgets.QAction(MainWindow)
        self.task_stats.setObjectName("task_stats")
        self.menu_test.addAction(self.add_test)
        self.menu_test.addAction(self.edit_test)
        self.menu_test.addAction(self.delete_test)
        self.menu_test.addSeparator()
        self.menu_test.addAction(self.quit)
        self.menubar.addAction(self.menu_test.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_add.setText(_translate("MainWindow", "Создать тест"))
        self.button_edit.setText(_translate("MainWindow", "Изменить тест"))
        self.button_delete.setText(_translate("MainWindow", "Удалить тест"))
        self.menu_test.setTitle(_translate("MainWindow", "Тест"))
        self.add_test.setText(_translate("MainWindow", "Создать"))
        self.edit_test.setText(_translate("MainWindow", "Изменить"))
        self.delete_test.setText(_translate("MainWindow", "Удалить"))
        self.quit.setText(_translate("MainWindow", "Выход"))
        self.pupil_res.setText(_translate("MainWindow", "По тесту..."))
        self.test_stats.setText(_translate("MainWindow", "Статистика теста"))
        self.task_stats.setText(_translate("MainWindow", "Статистика задания"))
